Repository bitnami/charts, pull requests merged in 2020-11, with the labels that each got.

#3850 [bitnami/wordpress] New major version
  bitnami/wordpress/Chart.lock
  bitnami/wordpress/Chart.yaml
  bitnami/wordpress/README.md
  bitnami/wordpress/ci/ct-values.yaml
  bitnami/wordpress/ci/values-hpa-pdb.yaml
  bitnami/wordpress/ci/values-metrics-and-ingress.yaml
  bitnami/wordpress/requirements.lock
  bitnami/wordpress/requirements.yaml
  bitnami/wordpress/templates/NOTES.txt
  bitnami/wordpress/templates/_helpers.tpl
  bitnami/wordpress/templates/deployment.yaml
  bitnami/wordpress/templates/externaldb-secrets.yaml
  bitnami/wordpress/templates/extra-list.yaml
  bitnami/wordpress/templates/hpa.yaml
  bitnami/wordpress/templates/ingress.yaml
  bitnami/wordpress/templates/metrics-svc.yaml
  bitnami/wordpress/templates/pdb.yaml
  bitnami/wordpress/templates/pvc.yaml
  bitnami/wordpress/templates/secrets.yaml
  bitnami/wordpress/templates/servicemonitor.yaml
  bitnami/wordpress/templates/svc.yaml
  bitnami/wordpress/templates/tests/test-mariadb-connection.yaml
  bitnami/wordpress/templates/tls-secrets.yaml
  bitnami/wordpress/values-production.yaml
  bitnami/wordpress/values.schema.json
  bitnami/wordpress/values.yaml
Labels: hacktoberfest-accepted

#4139 [bitnami/suitecrm] Move image to non root, use apiVersion: v2 and standardize chart
  bitnami/suitecrm/Chart.lock
  bitnami/suitecrm/Chart.yaml
  bitnami/suitecrm/README.md
  bitnami/suitecrm/requirements.lock
  bitnami/suitecrm/requirements.yaml
  bitnami/suitecrm/templates/NOTES.txt
  bitnami/suitecrm/templates/_helpers.tpl
  bitnami/suitecrm/templates/deployment.yaml
  bitnami/suitecrm/templates/externaldb-secrets.yaml
  bitnami/suitecrm/templates/extra-list.yaml
  bitnami/suitecrm/templates/ingress.yaml
  bitnami/suitecrm/templates/secrets.yaml
  bitnami/suitecrm/templates/suitecrm-pvc.yaml
  bitnami/suitecrm/templates/svc.yaml
  bitnami/suitecrm/values.yaml
Labels: hacktoberfest-accepted, on-hold

#3788 [bitnami/kubernetes-event-exporter] Introduce kubernetes-event-exporter
  bitnami/kubernetes-event-exporter/.helmignore
  bitnami/kubernetes-event-exporter/Chart.lock
  bitnami/kubernetes-event-exporter/Chart.yaml
  bitnami/kubernetes-event-exporter/README.md
  bitnami/kubernetes-event-exporter/templates/_helpers.tpl
  bitnami/kubernetes-event-exporter/templates/configmap.yaml
  bitnami/kubernetes-event-exporter/templates/deployment.yaml
  bitnami/kubernetes-event-exporter/templates/extra-list.yaml
  bitnami/kubernetes-event-exporter/templates/rbac.yaml
  bitnami/kubernetes-event-exporter/templates/serviceaccount.yaml
  bitnami/kubernetes-event-exporter/values.yaml
Labels: on-hold
