Repository bitnami/charts, pull requests merged in 2021-11, with the labels that each got.

#7819 Add new chart: Sonarqube
  bitnami/sonarqube/.helmignore
  bitnami/sonarqube/Chart.lock
  bitnami/sonarqube/Chart.yaml
  bitnami/sonarqube/README.md
  bitnami/sonarqube/ci/ct-values.yaml
  bitnami/sonarqube/ci/values-with-ingress-and-metrics.yaml
  bitnami/sonarqube/templates/NOTES.txt
  bitnami/sonarqube/templates/_helpers.tpl
  bitnami/sonarqube/templates/deployment.yaml
  bitnami/sonarqube/templates/externaldb-secret.yaml
  bitnami/sonarqube/templates/extra-list.yaml
  bitnami/sonarqube/templates/ingress.yaml
  bitnami/sonarqube/templates/jmx-configmap.yaml
  bitnami/sonarqube/templates/jmx-metrics-svc.yaml
  bitnami/sonarqube/templates/jmx-servicemonitor.yaml
  bitnami/sonarqube/templates/pvc.yaml
  bitnami/sonarqube/templates/secret.yaml
  bitnami/sonarqube/templates/service-account.yaml
  bitnami/sonarqube/templates/service.yaml
  bitnami/sonarqube/templates/tls-secret.yaml
  bitnami/sonarqube/values.yaml
Labels: new-chart

#8043 [bitnami/minio] WIP: Minio provisioning
  bitnami/minio/Chart.yaml
  bitnami/minio/README.md
  bitnami/minio/templates/provisioning-configmap.yaml
  bitnami/minio/templates/provisioning-job.yaml
  bitnami/minio/values.yaml
Labels: on-hold, new-chart

#6757 Explicitly only bootstrap the node specified by `galera.bootstrap.bootstrapFromNode`
  bitnami/mariadb-galera/Chart.yaml
  bitnami/mariadb-galera/templates/statefulset.yaml
Labels: on-hold

#7563 [bitnami/mariadb] Chart standarized
  bitnami/mariadb/Chart.yaml
  bitnami/mariadb/README.md
  bitnami/mariadb/templates/NOTES.txt
  bitnami/mariadb/templates/primary/configmap.yaml
  bitnami/mariadb/templates/primary/initialization-configmap.yaml
  bitnami/mariadb/templates/primary/pdb.yaml
  bitnami/mariadb/templates/primary/statefulset.yaml
  bitnami/mariadb/templates/primary/svc.yaml
  bitnami/mariadb/templates/role.yaml
  bitnami/mariadb/templates/rolebinding.yaml
  bitnami/mariadb/templates/secondary/configmap.yaml
  bitnami/mariadb/templates/secondary/pdb.yaml
  bitnami/mariadb/templates/secondary/statefulset.yaml
  bitnami/mariadb/templates/secondary/svc.yaml
  bitnami/mariadb/templates/secrets.yaml
  bitnami/mariadb/templates/serviceaccount.yaml
  bitnami/mariadb/templates/servicemonitor.yaml
  bitnami/mariadb/values.yaml
Labels: on-hold

#8133 bitnami/dataplatform-bp1: added annotation based discovery feature to wavefront and updated emitter/exporter images.
  bitnami/dataplatform-bp1/Chart.lock
  bitnami/dataplatform-bp1/Chart.yaml
  bitnami/dataplatform-bp1/README.md
  bitnami/dataplatform-bp1/templates/configmap.yaml
  bitnami/dataplatform-bp1/templates/exporter-deployment.yaml
  bitnami/dataplatform-bp1/templates/role.yaml
  bitnami/dataplatform-bp1/values.yaml
Labels: on-hold

#8018 [bitnami/rabbitmq] PodDisruptionBudget: support apiVersion policy/v1
  bitnami/rabbitmq/Chart.yaml
  bitnami/rabbitmq/templates/pdb.yaml
Labels: stale
