Repository bitnami/charts, pull requests merged in 2022-07, with the labels that each got.

#10901 [bitnami/rabbitmq] Allow to customize securityContext in volumePermission container
  bitnami/rabbitmq/Chart.yaml
  bitnami/rabbitmq/README.md
  bitnami/rabbitmq/templates/statefulset.yaml
  bitnami/rabbitmq/values.yaml
Labels: verify

#10978 [bitnami/keycloak] Make sure truststore files not exist before creation
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/templates/statefulset.yaml
Labels: verify

#10994 [bitnami/mysql] Run initscripts on secondary nodes
  bitnami/mysql/Chart.yaml
  bitnami/mysql/templates/secondary/statefulset.yaml
Labels: verify

#10881 [bitnami/postgresql] add warning regarding setting the password
  bitnami/postgresql/Chart.yaml
  bitnami/postgresql/README.md
Labels: verify

#10679 [bitnami/external-dns] Modify Cluster wide resources naming and add Helm Chart tests
  .vib/external-dns/goss/goss.yaml
  .vib/external-dns/vib-publish.json
  .vib/external-dns/vib-verify.json
  bitnami/external-dns/Chart.yaml
  bitnami/external-dns/templates/clusterrole.yaml
  bitnami/external-dns/templates/clusterrolebinding.yaml
  bitnami/external-dns/templates/psp-clusterrole.yaml
  bitnami/external-dns/templates/psp-clusterrolebinding.yaml
  bitnami/external-dns/templates/psp.yaml
Labels: verify

#11018 [bitnami/postgresql] Fix postgresql read servicemonitor scraping metrics on primary pod
  bitnami/postgresql/Chart.yaml
  bitnami/postgresql/templates/read/metrics-configmap.yaml
  bitnami/postgresql/templates/read/metrics-svc.yaml
  bitnami/postgresql/templates/read/servicemonitor.yaml
Labels: verify

#10990 [bitnami/keycloak] ingress/tls hostname template support
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/NOTES.txt
  bitnami/keycloak/templates/ingress.yaml
  bitnami/keycloak/templates/tls-secret.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#10999 [bitnami/nginx] Add custom container ports
  bitnami/nginx/Chart.yaml
  bitnami/nginx/README.md
  bitnami/nginx/templates/deployment.yaml
  bitnami/nginx/values.yaml
Labels: verify

#10910 [bitnami/keycloak] Fix Kubernetes discovery, add httpRelativePath to make migration easier
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/configmap-env-vars.yaml
  bitnami/keycloak/templates/statefulset.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#10652 [bitnami/matomo] Adding the Matomo Helm Chart
  .github/workflows/cd-pipeline.yaml
  .vib/matomo/cypress/cypress.json
  .vib/matomo/cypress/cypress/fixtures/images/post_image.png
  .vib/matomo/cypress/cypress/fixtures/users.json
  .vib/matomo/cypress/cypress/fixtures/websites.json
  .vib/matomo/cypress/cypress/integration/matomo_spec.js
  .vib/matomo/cypress/cypress/integration/utils.js
  .vib/matomo/cypress/cypress/support/commands.js
  .vib/matomo/cypress/cypress/support/index.js
  .vib/matomo/goss/goss.yaml
  .vib/matomo/vib-publish.json
  .vib/matomo/vib-verify.json
  bitnami/matomo/.helmignore
  bitnami/matomo/Chart.lock
  bitnami/matomo/Chart.yaml
  bitnami/matomo/README.md
  bitnami/matomo/templates/NOTES.txt
  bitnami/matomo/templates/_helpers.tpl
  bitnami/matomo/templates/deployment.yaml
  bitnami/matomo/templates/externaldb-secrets.yaml
  bitnami/matomo/templates/extra-list.yaml
  bitnami/matomo/templates/ingress.yaml
  bitnami/matomo/templates/networkpolicy-backend-ingress.yaml
  bitnami/matomo/templates/networkpolicy-egress.yaml
  bitnami/matomo/templates/networkpolicy-ingress.yaml
  bitnami/matomo/templates/pv.yaml
  bitnami/matomo/templates/pvc.yaml
  bitnami/matomo/templates/secrets.yaml
  bitnami/matomo/templates/svc.yaml
  bitnami/matomo/templates/tls-secrets.yaml
  bitnami/matomo/values.yaml
Labels: on-hold, new-product, verify

#11001 [bitnami/fluentd] Add init scripts support
  bitnami/fluentd/Chart.yaml
  bitnami/fluentd/README.md
  bitnami/fluentd/templates/_helpers.tpl
  bitnami/fluentd/templates/aggregator-init-configmap.yaml
  bitnami/fluentd/templates/aggregator-statefulset.yaml
  bitnami/fluentd/templates/forwarder-daemonset.yaml
  bitnami/fluentd/templates/forwarder-init-configmap.yaml
  bitnami/fluentd/values.yaml
Labels: verify

#11073 [bitnami/magento] Major version: Update Elasticsearch subchart
  bitnami/magento/Chart.lock
  bitnami/magento/Chart.yaml
  bitnami/magento/README.md
Labels: verify

#11049 [bitnami/rabbitmq] Allow set custom logging
  bitnami/rabbitmq/Chart.yaml
  bitnami/rabbitmq/README.md
  bitnami/rabbitmq/templates/statefulset.yaml
Labels: verify

#10823 bitnami/spring-cloud-dataflow: Fix for #10301: Apply server.containerPort as documented.
  bitnami/spring-cloud-dataflow/Chart.lock
  bitnami/spring-cloud-dataflow/Chart.yaml
  bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
Labels: verify

#11095 [bitnami/keycloak] Do not expose https port if tls is not enabled
  bitnami/keycloak/Chart.lock
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/NOTES.txt
  bitnami/keycloak/templates/service.yaml
  bitnami/keycloak/templates/statefulset.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#11128 [bitnami/mongodb] Fix commonAnnotations when working with external access svc
  bitnami/mongodb/Chart.yaml
  bitnami/mongodb/templates/replicaset/external-access-svc.yaml
Labels: verify

#11117 [bitnami/rabbitmq] Fix high CPU usage while idle
  bitnami/rabbitmq/Chart.yaml
  bitnami/rabbitmq/templates/statefulset.yaml
Labels: verify

#11051 [bitnami/thanos] Creates separate service for grpc port of query module
  bitnami/thanos/Chart.lock
  bitnami/thanos/Chart.yaml
  bitnami/thanos/README.md
  bitnami/thanos/templates/query/ingress-grpc.yaml
  bitnami/thanos/templates/query/service-grpc-headless.yaml
  bitnami/thanos/templates/query/service-grpc.yaml
  bitnami/thanos/templates/query/service-headless.yaml
  bitnami/thanos/templates/query/service.yaml
  bitnami/thanos/values.yaml
Labels: verify

#10668 [bitnami/grafana-loki] Implement query-scheduler configuration
  bitnami/grafana-loki/Chart.yaml
  bitnami/grafana-loki/README.md
  bitnami/grafana-loki/templates/_helpers.tpl
  bitnami/grafana-loki/templates/querier/statefulset.yaml
  bitnami/grafana-loki/templates/query-frontend/deployment.yaml
  bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
  bitnami/grafana-loki/templates/query-scheduler/service.yaml
  bitnami/grafana-loki/values.yaml
Labels: verify

#10979 [bitnami/thanos] feat: update default prometheusrule value
  bitnami/thanos/Chart.yaml
  bitnami/thanos/README.md
  bitnami/thanos/templates/prometheusrule.yaml
  bitnami/thanos/values.yaml
Labels: verify

#11143 [bitnami/matomo] Fix category case
  bitnami/matomo/Chart.yaml
Labels: verify

#11093 [bitnami/external-dns] Fix issue with psp-cluster-role
  bitnami/external-dns/Chart.yaml
  bitnami/external-dns/templates/psp-clusterrole.yaml
Labels: verify

#11082 [bitnami/drupal] Add ServiceAccount
  bitnami/drupal/Chart.yaml
  bitnami/drupal/README.md
  bitnami/drupal/templates/_helpers.tpl
  bitnami/drupal/templates/deployment.yaml
  bitnami/drupal/templates/serviceaccount.yaml
  bitnami/drupal/values.schema.json
  bitnami/drupal/values.yaml
Labels: verify

#11158 [bitnami/zookeeper] fix - service.headless.annitations is inoperative when i do not set the configuration of service.annotations
  bitnami/zookeeper/Chart.yaml
  bitnami/zookeeper/templates/svc-headless.yaml
Labels: verify

#11137 [bitnami/common] Affinities section does not use common.names.namespace
  bitnami/common/Chart.yaml
  bitnami/common/templates/_affinities.tpl
Labels: verify

#11173 [bitnami/airflow] Update Redis subchart
  bitnami/airflow/Chart.lock
  bitnami/airflow/Chart.yaml
  bitnami/airflow/README.md
Labels: verify

#11172 [bitnami/argo-cd] Update Redis subchart
  bitnami/argo-cd/Chart.lock
  bitnami/argo-cd/Chart.yaml
  bitnami/argo-cd/README.md
Labels: verify

#11174 [bitnami/kubeapps] Update Redis subchart
  bitnami/kubeapps/Chart.lock
  bitnami/kubeapps/Chart.yaml
Labels: verify

#11170 [bitnami/harbor] Update Redis subchart
  bitnami/harbor/Chart.lock
  bitnami/harbor/Chart.yaml
Labels: verify

#11171 [bitnami/discourse] Update Redis subchart
  bitnami/discourse/Chart.lock
  bitnami/discourse/Chart.yaml
Labels: verify

#10828 [bitnami/mongodb-sharded] Use common helper to manage app secrets
  bitnami/mongodb-sharded/Chart.yaml
  bitnami/mongodb-sharded/templates/secrets.yaml
Labels: verify

#11183 [bitnami/oauth2-proxy] Update Redis subchart
  bitnami/oauth2-proxy/Chart.lock
  bitnami/oauth2-proxy/Chart.yaml
  bitnami/oauth2-proxy/README.md
Labels: verify

#11139 [bitnami/php-my-admin] Fix cert-manager feature flag behaviour, clarify tls secret config
  bitnami/phpmyadmin/Chart.yaml
  bitnami/phpmyadmin/README.md
  bitnami/phpmyadmin/templates/ingress.yaml
  bitnami/phpmyadmin/templates/tls-secrets.yaml
  bitnami/phpmyadmin/values.yaml
Labels: verify

#11090 [bitnami/solr] enable Solr metrics to work when basic auth is enabled
  bitnami/solr/Chart.lock
  bitnami/solr/Chart.yaml
  bitnami/solr/README.md
  bitnami/solr/templates/metrics-deployment.yaml
  bitnami/solr/templates/metrics-svc.yaml
  bitnami/solr/templates/servicemonitor.yaml
  bitnami/solr/values.yaml
Labels: verify

#11178 [bitnami/thanos] fix Deprecation Warning of thanos
  bitnami/thanos/Chart.yaml
  bitnami/thanos/templates/query/deployment.yaml
Labels: verify

#11142 [bitnami/mariadb] add option for extraVolumeMounts to MariaDB metrics containers
  bitnami/mariadb/Chart.yaml
  bitnami/mariadb/README.md
  bitnami/mariadb/templates/primary/statefulset.yaml
  bitnami/mariadb/templates/secondary/statefulset.yaml
  bitnami/mariadb/values.yaml
Labels: verify

#10976 [bitnami/keycloak] switch to default keycloak port 8080, while scraping metrics
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/metrics-service.yaml
  bitnami/keycloak/templates/servicemonitor.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#11133 [bitnami/rabbitmq-cluster-operator] add commonName to the rabbitmq-operator certificate
  bitnami/rabbitmq-cluster-operator/Chart.yaml
  bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/certificate.yaml
Labels: verify

#11165 [bitnami/redis-cluster] Allow specifying metrics container security context
  bitnami/redis-cluster/Chart.yaml
  bitnami/redis-cluster/README.md
  bitnami/redis-cluster/templates/redis-statefulset.yaml
  bitnami/redis-cluster/values.yaml
Labels: verify

#11212 [bitnami/minio] allow empty s3 creds when using iam role for sa
  bitnami/minio/Chart.yaml
  bitnami/minio/README.md
  bitnami/minio/templates/_helpers.tpl
Labels: verify

#11167 [bitnami/mysql] Allow custom name of database role
  bitnami/mysql/Chart.yaml
  bitnami/mysql/README.md
  bitnami/mysql/templates/_helpers.tpl
  bitnami/mysql/values.yaml
Labels: verify

#11229 [bitnami/grafana-loki] Bump chart version
  bitnami/grafana-loki/Chart.yaml
Labels: verify

#11124 [bitnami/keycloak] make metrics scrape target configurable
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/servicemonitor.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#11048 [bitnami/elasticsearch] Implemented custom annotations for all Elasticsearch statefulsets
  bitnami/elasticsearch/Chart.yaml
  bitnami/elasticsearch/README.md
  bitnami/elasticsearch/templates/coordinating/statefulset.yaml
  bitnami/elasticsearch/templates/data/statefulset.yaml
  bitnami/elasticsearch/templates/ingest/statefulset.yaml
  bitnami/elasticsearch/templates/master/statefulset.yaml
  bitnami/elasticsearch/values.yaml
Labels: verify

#11191 [bitnami/spring-cloud-dataflow] use common tpl function instead of toYaml
  bitnami/spring-cloud-dataflow/Chart.yaml
  bitnami/spring-cloud-dataflow/templates/prometheus-proxy/deployment.yaml
  bitnami/spring-cloud-dataflow/templates/prometheus-proxy/service.yaml
  bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
  bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
  bitnami/spring-cloud-dataflow/templates/server/ingress.yaml
  bitnami/spring-cloud-dataflow/templates/server/service.yaml
  bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml
  bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml
  bitnami/spring-cloud-dataflow/templates/skipper/service.yaml
Labels: verify

#11245 Adding workflows for the support by using the GH board
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/.env
  .github/workflows/clossing-issues.yml
  .github/workflows/comments.yml
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
  .github/workflows/sync-labels.yml
  .github/workflows/triage.yml
Labels: bitnami

#11176 [bitnami/keycloak] Allow overriding namespace via values
  bitnami/keycloak/Chart.yaml
  bitnami/keycloak/README.md
  bitnami/keycloak/templates/NOTES.txt
  bitnami/keycloak/templates/configmap-env-vars.yaml
  bitnami/keycloak/templates/configmap.yaml
  bitnami/keycloak/templates/headless-service.yaml
  bitnami/keycloak/templates/hpa.yaml
  bitnami/keycloak/templates/ingress.yaml
  bitnami/keycloak/templates/init-scripts-configmap.yaml
  bitnami/keycloak/templates/keycloak-config-cli-configmap.yaml
  bitnami/keycloak/templates/keycloak-config-cli-job.yaml
  bitnami/keycloak/templates/metrics-service.yaml
  bitnami/keycloak/templates/networkpolicy.yaml
  bitnami/keycloak/templates/pdb.yaml
  bitnami/keycloak/templates/role.yaml
  bitnami/keycloak/templates/rolebinding.yaml
  bitnami/keycloak/templates/secrets.yaml
  bitnami/keycloak/templates/service.yaml
  bitnami/keycloak/templates/serviceaccount.yaml
  bitnami/keycloak/templates/servicemonitor.yaml
  bitnami/keycloak/templates/statefulset.yaml
  bitnami/keycloak/templates/tls-secret.yaml
  bitnami/keycloak/values.yaml
Labels: verify

#11281 Adding two team members to the BITNAMI_TEAM
  .github/workflows/.env
Labels: bitnami

#11292 Avoid assigning reviewers for the bitnami-bot PRs
  .github/workflows/triage.yml
Labels: bitnami

#11224 [bitnami/nginx] Fix TLS setup for externally provided TLS certificates
  bitnami/nginx/Chart.yaml
  bitnami/nginx/templates/health-ingress.yaml
  bitnami/nginx/templates/ingress.yaml
Labels: verify, in-progress, nginx

#11302 [bitnami/*] Disable CI in closed PRs
  .github/workflows/ci-pipeline.yaml
Labels: bitnami

#11308 [bitnami/*] Ignoring automated PR (Release activity) from the support flow.
  .github/workflows/comments.yml
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
  .github/workflows/triage.yml
Labels: bitnami

#11293 [bitnami/elasticsearch] fix elasticsearch tls secret
  bitnami/elasticsearch/Chart.yaml
  bitnami/elasticsearch/templates/secrets.yaml
Labels: verify, triage

#11309 [bitnami/keycloak] Update documentation about external database configuration
  bitnami/keycloak/README.md
Labels: bitnami

#11298 [bitnami/redis] Add timeout to redis-cli in start-sentinel.sh
  bitnami/redis/Chart.yaml
  bitnami/redis/templates/scripts-configmap.yaml
Labels: verify, triage, redis

#11330 Add marcosbc to support assignation
  .github/workflows/.env
Labels: bitnami

#11288 [bitnami/mariadb] Allow custom name of database role
  bitnami/mariadb/Chart.yaml
  bitnami/mariadb/README.md
  bitnami/mariadb/templates/_helpers.tpl
  bitnami/mariadb/values.yaml
Labels: verify, triage, mariadb

#11328 [bitnami/dataplatform-bp2] Deprecate Helm chart
  .vib/dataplatform-bp2/vib-publish.json
  bitnami/dataplatform-bp2/Chart.lock
  bitnami/dataplatform-bp2/Chart.yaml
  bitnami/dataplatform-bp2/README.md
  bitnami/dataplatform-bp2/templates/NOTES.txt
  bitnami/dataplatform-bp2/templates/_helpers.tpl
  bitnami/dataplatform-bp2/templates/configmap.yaml
  bitnami/dataplatform-bp2/templates/emitter-deployment.yaml
  bitnami/dataplatform-bp2/templates/emitter-svc.yaml
  bitnami/dataplatform-bp2/templates/exporter-deployment.yaml
  bitnami/dataplatform-bp2/templates/exporter-svc.yaml
  bitnami/dataplatform-bp2/templates/extra-list.yaml
  bitnami/dataplatform-bp2/templates/role.yaml
  bitnami/dataplatform-bp2/templates/rolebinding.yaml
  bitnami/dataplatform-bp2/templates/serviceaccount.yaml
  bitnami/dataplatform-bp2/values.schema.json
  bitnami/dataplatform-bp2/values.yaml
Labels: bitnami

#11331 [bitnami/dataplatform-bp2] Add dataplatform-bp2 to cd-pipeline.yaml
  .github/workflows/cd-pipeline.yaml
Labels: bitnami

#11332 [bitnami/dataplatform-bp2] Bump chart version in Chart.yaml
  bitnami/dataplatform-bp2/Chart.yaml
Labels: bitnami

#11334 Fixing regression when an issue is created by non bitnami-bot
  .github/workflows/comments.yml
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
  .github/workflows/triage.yml
Labels: bitnami

#11335 [bitnami/*] Simplify condition for triage workflow
  .github/workflows/triage.yml
Labels: bitnami

#11333 [bitnami/dataplatform-bp2] Deprecate Helm chart. Remove source code
  .github/workflows/cd-pipeline.yaml
  .vib/dataplatform-bp2/vib-publish.json
  bitnami/dataplatform-bp2/Chart.lock
  bitnami/dataplatform-bp2/Chart.yaml
  bitnami/dataplatform-bp2/README.md
  bitnami/dataplatform-bp2/templates/NOTES.txt
  bitnami/dataplatform-bp2/templates/_helpers.tpl
  bitnami/dataplatform-bp2/templates/configmap.yaml
  bitnami/dataplatform-bp2/templates/emitter-deployment.yaml
  bitnami/dataplatform-bp2/templates/emitter-svc.yaml
  bitnami/dataplatform-bp2/templates/exporter-deployment.yaml
  bitnami/dataplatform-bp2/templates/exporter-svc.yaml
  bitnami/dataplatform-bp2/templates/extra-list.yaml
  bitnami/dataplatform-bp2/templates/role.yaml
  bitnami/dataplatform-bp2/templates/rolebinding.yaml
  bitnami/dataplatform-bp2/templates/serviceaccount.yaml
  bitnami/dataplatform-bp2/values.schema.json
  bitnami/dataplatform-bp2/values.yaml
Labels: bitnami

#11337 [bitnami/*] Fixing the race condition only to exclude bitnami-bot ON auto-merge PRs
  .github/workflows/comments.yml
Labels: bitnami

#11300 [bitnami/rabbitmq] Fix volume-permissions initContainer if runAsUser is auto
  bitnami/rabbitmq/Chart.yaml
  bitnami/rabbitmq/templates/statefulset.yaml
Labels: verify, in-progress, rabbitmq

#11351 [bitnami/jenkins] Update new version of Jenkins 2.346.2
  .vib/jenkins/cypress/cypress/integration/jenkins_spec.js
  bitnami/jenkins/Chart.lock
  bitnami/jenkins/Chart.yaml
  bitnami/jenkins/README.md
  bitnami/jenkins/values.yaml
Labels: verify, bitnami

#11307 [bitnami/*] Migrate logic for automated PRs to GitHub's CI
  .github/workflows/ci-pipeline.yaml
Labels: bitnami

#11349 [bitnami/redis-cluster] Update redis-default config
  bitnami/redis-cluster/Chart.yaml
  bitnami/redis-cluster/templates/configmap.yaml
Labels: verify, bitnami

#11274 [bitnami/thanos] Conditionally Set objstore arg and OBJSTORE_CONFIG for Thanos receive
  bitnami/thanos/Chart.yaml
  bitnami/thanos/templates/receive/statefulset.yaml
Labels: verify, thanos

#11313 [bitnami/redis] Fix OutOfSync HPAs with ArgoCD
  bitnami/redis/Chart.yaml
  bitnami/redis/templates/replicas/hpa.yaml
  bitnami/redis/templates/sentinel/hpa.yaml
Labels: verify, triage

#11175 [bitnami/*] Make cd-pipeline retryable
  .github/workflows/cd-pipeline.yaml
Labels: bitnami

#11378 [bitnami/*] Use bitnami-bot to manage auto-merge in automated PRs
  .github/workflows/ci-pipeline.yaml
Labels: bitnami

#11338 [bitnami/schema-registry] Add schema-registry chart
  .github/workflows/cd-pipeline.yaml
  .vib/schema-registry/vib-publish.json
  .vib/schema-registry/vib-verify.json
  bitnami/schema-registry/.helmignore
  bitnami/schema-registry/Chart.lock
  bitnami/schema-registry/Chart.yaml
  bitnami/schema-registry/README.md
  bitnami/schema-registry/templates/NOTES.txt
  bitnami/schema-registry/templates/_helpers.tpl
  bitnami/schema-registry/templates/configmap.yaml
  bitnami/schema-registry/templates/external-kafka-secrets.yaml
  bitnami/schema-registry/templates/extra-list.yaml
  bitnami/schema-registry/templates/headless-service.yaml
  bitnami/schema-registry/templates/hpa.yaml
  bitnami/schema-registry/templates/ingress.yaml
  bitnami/schema-registry/templates/log4j-configmap.yaml
  bitnami/schema-registry/templates/pdb.yaml
  bitnami/schema-registry/templates/service.yaml
  bitnami/schema-registry/templates/serviceaccount.yaml
  bitnami/schema-registry/templates/statefulset.yaml
  bitnami/schema-registry/templates/tls-secret.yaml
  bitnami/schema-registry/values.yaml
Labels: verify, bitnami

#11398 [bitnami/mongodb] Change endpoint for metrics liveness and readiness probes
  bitnami/mongodb/Chart.yaml
  bitnami/mongodb/templates/hidden/statefulset.yaml
  bitnami/mongodb/templates/replicaset/statefulset.yaml
  bitnami/mongodb/templates/standalone/dep-sts.yaml
Labels: verify, bitnami, mongodb

#11370 [bitnami/airflow] Revisit Goss/Cypress tests
  .vib/airflow/cypress/cypress/fixtures/variables.json
  .vib/airflow/cypress/cypress/integration/airflow_spec.js
  .vib/airflow/cypress/cypress/support/commands.js
  .vib/airflow/cypress/cypress/support/utils.js
  .vib/airflow/goss/goss.yaml
Labels: verify, airflow, bitnami

#11401 [bitnami/consul] Revisit Goss/Cypress tests
  .vib/consul/cypress/cypress/integration/consul_spec.js
  .vib/consul/goss/goss.yaml
  .vib/consul/goss/vars.yaml
  .vib/consul/vib-publish.json
  .vib/consul/vib-verify.json
Labels: bitnami, consul

#11355 Parametrizing support flow by using GH teams and fixing and fixing an issue with comments
  .github/workflows/.env
  .github/workflows/move-closed-issues.yml
  .github/workflows/moving-cards.yml
  .github/workflows/sync-labels.yml
  .github/workflows/sync-teams.yml
  .github/workflows/triage.yml
Labels: bitnami

#11427 [bitnami/fluentd] Add GOSS tests and publish using VIB
  .github/workflows/cd-pipeline.yaml
  .vib/fluentd/goss/goss.yaml
  .vib/fluentd/vib-publish.json
  .vib/fluentd/vib-verify.json
  bitnami/fluentd/Chart.yaml
  bitnami/fluentd/templates/forwarder-clusterrole.yaml
  bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml
  bitnami/fluentd/templates/forwarder-psp.yaml
Labels: bitnami

#11403 [bitnami/mariadb] Revisit GOSS tests
  .vib/mariadb/goss/goss.yaml
  .vib/mariadb/goss/vars.yaml
  .vib/mariadb/vib-publish.json
  .vib/mariadb/vib-verify.json
Labels: mariadb, bitnami
